name: do-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Release
        uses: BigWigsMods/packager@master
        env:
          #CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          #WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
